name: Build ICS File

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install deps
        run: pip install pandas ics || true
      - name: Run build script
        run: python build_ics.py
      - name: Upload ICS file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hilal-ics
          path: |
            **/*.ics
